name: SonarQube Scan

on:
  push:
    branches:
      - main
      - master

jobs:
  sonar:
    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v4

      - name: Sonar Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://localhost:9000
